# Generated by Django 4.2 on 2024-12-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_option_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(choices=[('creator', 'CREATOR'), ('taker', 'TAKER')], default='taker', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'option_text'), name='unique_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('survey', 'question_text'), name='unique_question_per_survey'),
        ),
    ]
