# Generated by Django 4.2 on 2024-11-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_userprofile_role_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
